[package]
name = "progenitor-middleware"
version = "0.12.5"
edition = "2021"
license = "MPL-2.0"
description = "An OpenAPI client generator"
repository = "https://github.com/sammccord/progenitor.git"
readme = "../README.md"
keywords = ["openapi", "openapiv3", "sdk", "generator", "proc_macro"]
categories = ["api-bindings", "compilers"]

[features]
default = ["macro"]
macro = ["dep:progenitor-middleware-client", "dep:progenitor-middleware-macro"]

[dependencies]
progenitor-middleware-client = { workspace = true, optional = true }
progenitor-middleware-impl = { workspace = true }
progenitor-middleware-macro = { workspace = true, optional = true }

[dev-dependencies]
base64 = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
percent-encoding = { workspace = true }
rand = { workspace = true }
regress = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
